builders:
  easyLocalizationGenerator:
    import: "package:easy_localization_generator/builder.dart"
    builder_factories: ["localizationGenerator"]
    build_extensions: {".dart": [".localization_generator.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]