name: easy_localization_generator_plus
description: Generates the localization keys from an online Google Sheet or a local csv file.
version: 0.0.1
# author: Tony Truong <tony.truong.dev@gmail.com>
homepage: https://github.com/truongthien94/easy_localization_generator
issue_tracker: https://github.com/truongthien94/easy_localization_generator/issues

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  build: ^2.4.1
  build_config: ^1.1.1
  source_gen: ^1.5.0
  http: ^1.2.1
  path: ^1.9.0
  csv: ^6.0.0
  intl: ^0.20.2
  analyzer: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
